"""add blacklist table

Revision ID: 7ee156d9db15
Revises: 971484dce56d
Create Date: 2019-02-06 14:45:56.258333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ee156d9db15'
down_revision = '971484dce56d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('text', sa.String(length=500), nullable=False),
    sa.Column('complete', sa.Boolean(), nullable=False),
    sa.Column('author', sa.String(length=100), nullable=False),
    sa.Column('datecreated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todo')
    # ### end Alembic commands ###
