"""add blacklist table

Revision ID: 971484dce56d
Revises: b8aab12326b8
Create Date: 2019-02-06 14:13:42.074136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '971484dce56d'
down_revision = 'b8aab12326b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('text', sa.String(length=500), nullable=False),
    sa.Column('complete', sa.Boolean(), nullable=False),
    sa.Column('user', sa.String(length=100), nullable=False),
    sa.Column('datecreated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todo')
    # ### end Alembic commands ###
