"""add todo table

Revision ID: b8aab12326b8
Revises: 6e7a22428e33
Create Date: 2019-02-06 10:44:17.427461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8aab12326b8'
down_revision = '6e7a22428e33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('text', sa.String(length=500), nullable=False),
    sa.Column('complete', sa.Boolean(), nullable=False),
    sa.Column('user', sa.String(length=50), nullable=False),
    sa.Column('datecreated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('text'),
    sa.UniqueConstraint('user')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todo')
    # ### end Alembic commands ###
